project:
  type: book

book:
  title: "cbl_book"
  author: "CompBio Lab"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  repo-actions:
    - source
  repo-url: "https://github.com/CompBio-Lab/CompBio-Lab.github.io"
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

